security.basic.enable: false
management.security.enabled: false
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
         uri: https://github.com/amuratech/jarvis
         searchPaths: spring-cloud/cloud-config
          # uri: file:////Users/labtocat/Code/Amura/SpringCloud/cloud-config
